#!/bin/bash

sudo apt update -y
sudo apt install -y docker.io

sudo systemctl start docker
sudo systemctl enable docker

sudo usermod -aG docker $USER

echo "Docker installed & running "
echo "Logout/login once to use docker without sudo"
